# Generated by Django 2.2.5 on 2019-09-23 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('topics', models.CharField(max_length=200, verbose_name='类别')),
                ('tags', models.CharField(max_length=200, verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='账户')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('poster', models.ImageField(upload_to='images/authos/', verbose_name='头像')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='内容')),
                ('prop', models.CharField(max_length=200, verbose_name='属性词')),
                ('adj', models.CharField(max_length=200, verbose_name='形容词')),
                ('sentiment', models.IntegerField(default=1, verbose_name='情感')),
                ('begin_pos', models.IntegerField(default=-1, verbose_name='开始位置')),
                ('end_pos', models.IntegerField(default=-1, verbose_name='结束位置')),
                ('abstract', models.TextField(verbose_name='摘要')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.Article', verbose_name='文章')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.Author', verbose_name='作者'),
        ),
    ]
